# Read the Docs configuration file
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
   configuration: module_4/docs/conf.py

python:
   install:
   - requirements: module_4/requirements.txt
   # Remove this line that's causing the error:
   # - method: pip
   #   path: module_4

formats:
  - pdf
  - epub
